env:
  global:
    secure: UwdKDjxRCHfj2nCYrdHgYx8MkfnL/P23vSBJcbWQsdf64uIJLynyJ6tpUdurdHV8se+/1S+YvASBsfumJIMiCcwLaAgwmO3z+HYwfZvEWb4HT1kjuUnz13ZQwswlb6SFQJEPp0gb1zKthjGjdFupWLieqLwjerD/gs91NFC2ycI=

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.4"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi

script:
  - vendor/bin/phpunit --verbose $PHPUNIT_FLAGS

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
    fi
